# Generated by Django 5.2.1 on 2025-05-29 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_jobpost_delete_job_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='decscription',
            new_name='description',
        ),
    ]
